name: Notify Water Level

on:
  schedule:
    - cron: '0 2 * * *'  # 09:00 Thailand time (UTC+7 = UTC 2)
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        # เพิ่ม selenium และ webdriver-manager สำหรับการดึงข้อมูลจากเว็บที่ใช้ JavaScript
        run: pip install requests pytz beautifulsoup4 selenium webdriver-manager

      - name: Run main.py
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        run: python main.py
