name: Notify Water Level

on:
  schedule:
    # แก้ไขเวลาแจ้งเตือนตามที่ต้องการ
    - cron: '0 1 * * *'  # 08:00 น. ตามเวลาประเทศไทย (UTC+7)
    - cron: '0 10 * * *' # 17:00 น. ตามเวลาประเทศไทย (UTC+7)
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests pytz beautifulsoup4 selenium webdriver-manager selenium-stealth

      - name: Run main.py
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        run: python main.py
