name: Notify Facebook Page

on:
  schedule:
    - cron: '0 1 * * *'  # 08:00 น. (เวลาประเทศไทย UTC+7)
    - cron: '0 10 * * *' # 17:00 น. (เวลาประเทศไทย UTC+7)
  workflow_dispatch:

jobs:
  notify-facebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run notify script
        env:
          FACEBOOK_PAGE_ACCESS_TOKEN: ${{ secrets.FACEBOOK_PAGE_ACCESS_TOKEN }}
        run: |
          python notify.py
